# Generated by Django 5.1.1 on 2024-10-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PDFEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teacher_id", models.CharField(max_length=1000)),
                ("vector_store_id", models.CharField(max_length=1000)),
                ("file_name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="pdfs/")),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("standard", models.CharField(max_length=10)),
                ("contact_number", models.CharField(max_length=15)),
                ("parent_email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("tagline", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("greetings", models.CharField(max_length=255)),
                ("prompt", models.CharField(max_length=2000)),
                ("subject", models.CharField(max_length=100)),
                ("assistant_id", models.CharField(max_length=1000)),
                ("vector_store_id", models.CharField(max_length=1000)),
            ],
        ),
    ]
